global:
  scrape_interval: 5s
scrape_configs:
  - job_name: my-app
    honor_timestamps: true
    metrics_path: /q/metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8080